string integrator                  # Integrator type used by OpenSim
float64 integrator_accuracy        # Integrator accuracy (maximal error)
float64 min_step_size              # Minimal internal time step for integrator
float64 stiffness                  # Default stiffness used for material if none is specified in SDF
float64 dissipation                # Default dissipation used for material if none is specified in SDF
float64 transition_velocity         # Default transition velocity used for friction if none is specified in SDF
float64 static_friction             # Default static friction coefficient used if none is specified in SDF
float64 dynamic_friction            # Default dynamic friction coefficient used if none is specified in SDF
float64 viscous_friction            # Default viscous friction coefficient used if none is specified in SDF
